version: '3.7'

services:
  web:
    build: .
    volumes: &web-volumes
      - &app-volume .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    ports:
      - 587:587
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
      - redis
      - sidekiq
    environment: &web-environment
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      MAILER_ADDRESS: smtp.gmail.com
      MAILER_PORT: 587
      MAILER_DOMAIN: taskmanager.com
      MAILER_AUTHENTICATION: plain
      HOST: 0.0.0.0:3000
      PRODUCTION_HOST: sleepy-brushlands-18624.herokuapp.com
      REDIS_URL: redis://redis
      COVERALLS_TOKEN: cb3By1upKJctZv4k1S7XoTuFneDhjmnhP
      ROLLBAR_TOKEN: 88a2e474717f4a4fa30665d87a08ee14
      NEWRELIC_TOKEN: eu01xx442c267b5cf7fafdc68f09316eb7a5NRAL
    command: bundle exec rails s -b '0.0.0.0' -p 3000

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  sidekiq:
    build: .
    command: bundle exec sidekiq -C /app/config/sidekiq.yml
    environment: *web-environment
    volumes: *web-volumes
    depends_on:
      - redis

  redis:
    image: redis:5.0.9-alpine

volumes:
  bundle_cache: