version: '3.7'

services:
  web:
    build: .
    volumes: &web-volumes
      - &app-volume .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    ports:
      - 587:587
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
    environment: &web-environment
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      MAILER_USERNAME: development.work73@gmail.com
      MAILER_PASSWORD: taskmanager73
      MAILER_ADDRESS: smtp.gmail.com
      MAILER_PORT: 587
      MAILER_DOMAIN: taskmanager.com
      MAILER_AUTHENTICATION: plain
      LOCAL_HOST: 0.0.0.0:3000
      PRODUCTION_HOST: sleepy-brushlands-18624.herokuapp.com
      REDIS_URL: redis://redis
    command: bundle exec rails s -b '0.0.0.0' -p 3000

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:5.0.9-alpine

volumes:
  bundle_cache: