common: &default_settings
  license_key: $NEWRELIC_TOKEN
  app_name: TaskManager
  log_level: info

development:
  <<: *default_settings
  app_name: TaskManager (Development)

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: TaskManager (Staging)

production:
  <<: *default_settings
